### ISSUE TITLE
cf command to add a credhub secret fails with error

### ISSUE THREAD

**Issue by sudheerrao** [pivotal-cf/spring-cloud-services-cli-plugin#105]
I am trying to add a secret using cf config-server-add-credhub-secret command. it fails with error: failed to add secret or is not supported by this config server
The config server that is being used is SCS3.1.4 (p.config-server). Here is a sample command:

$f config-server-add-credhub-secret customerconfig customerservice/devphx/master/custsecret '{"Test": "3432"}'

**Comment by kvmw** [comment]
Please make sure credhub is enabled in SCS installation. 

`Ops Manager` >> `Spring Cloud Services` Tile >> `Settings` Tab >> `SCS Service Broker`. 

 Make sure `Enable credhub as a backend for config server` is selected.
