### ISSUE TITLE
BUG: CLI returns `Successfully refreshed mirrors` when mirror-service refresh fails

### ISSUE THREAD

**Issue by LittleBaiBai** [pivotal-cf/spring-cloud-services-cli-plugin#112]
When mirror-service failed to sync due to #1601, the CLI command returns `Successfully refreshed mirrors`. The dashboard would show `failed` as `sync status` when `synchronize mirrors` button is clicked in this case. So I suspect the CLI is not parsing the response correctly.

**Comment by LittleBaiBai** [comment]
[Our CLI only checks for response status to be 200](https://github.com/pivotal-cf/spring-cloud-services-cli-plugin/blob/master/config/refresher.go#L38) to decide whether mirror refresh is successful. However, to display refresh status for all mirrors on the dashboard, the endpoint was updated to return 200 with status `FAILED` in the response body.

Sample response:
```
{"https://scs-gitlab.springapps.io/acceptance/refresh-test":{"commitId":"1b78d2b278608cc489bdba69eb849e842d971f51","status":"FAILED"}}
```

To fix this, we need to update the CLI to parse the response and return status accordingly.

**Comment by spikymonkey** [comment]
Another way to look at this would be to only return a 200 if all the updates were successful, which would save us from having to re-release the CLI. Wdyt?

**Comment by spikymonkey** [comment]
Removing this from the HA Epic as I don't think it's related...

**Comment by LittleBaiBai** [comment]
>only return a 200 if all the updates were successful

You mean changing the current config server dashboard to take response other than `200`? What status code can we use to indicate a partial success or no success?

**Comment by spikymonkey** [comment]
207 (multi status)?

**Comment by kvmw** [comment]
Since proper implementation of 207 (multi status) required changing the response body ([to include status codes)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/207) and that would have been a breaking change in the API, I ended up changing the plugin to parse the current response body.
