### ISSUE TITLE
Version 1.0.24 64-bit can't be installed on Ubuntu 20.04

### ISSUE THREAD

**Issue by tremblaysimon** [pivotal-cf/spring-cloud-services-cli-plugin#142]
### Describe the bug

When trying to install spring-cloud-services cf CLI plugin on Ubuntu 20.04, it doesn't work. There is those errors: 

```
Do you want to install the plugin spring-cloud-services-cli-plugin-linux-amd64-1.0.24? [yN]: y
/root/.cf/plugins/temp2815780770/3122232832: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/.cf/plugins/temp2815780770/3122232832)
/root/.cf/plugins/temp2815780770/3122232832: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/.cf/plugins/temp2815780770/3122232832)
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
root@54ef4f74d7bf:/#
```

so the plugin can't be installed.

### Reproduction steps

Assuming you are running on Ubuntu 20.04:

1. Run `cf install-plugin spring-cloud-services`
2. Observe the errors mentionned here.

### Expected behavior

The 64-bit 1.0.24 version of the plugin can be installed without any error.

### Additional context

Workaround is to use the 32-bit version.
Tried with cf CLI v7 and v8

**Comment by kvmw** [comment]
fixed in v1.0.25
