### ISSUE TITLE
Some dependencies missing from vendor directory

### ISSUE THREAD

**Issue by glyn** [pivotal-cf/spring-cloud-services-cli-plugin#42]
Steps to reproduce:

1. Get the latest level of the source code.
2. `rm $GOPATH/src/github.com/mattn/go-colorable`.
3. Build:
```
govendor install -ldflags="-X main.pluginVersion=$(cat version)" +local
```

The build fails as follows:
```
vendor/github.com/fatih/color/color.go:10:2: cannot find package "github.com/mattn/go-colorable" in any of:
	/Users/gnormington/go/src/github.com/pivotal-cf/spring-cloud-services-cli-plugin/vendor/github.com/mattn/go-colorable (vendor tree)
	/usr/local/opt/go/libexec/src/github.com/mattn/go-colorable (from $GOROOT)
	/Users/gnormington/go/src/github.com/mattn/go-colorable (from $GOPATH)
Error: exit status 1
```

Thanks to @aclement for pointing this out.

**Comment by aclement** [comment]
Should we be including *everything* in the vendor directory in version control? Is it not just enough to include vendor/vendor.json ?

**Comment by glyn** [comment]
There are various schools of thought. This plugin has opted to check all the dependencies into the `vendor` directory. This has some benefits (build jobs are less likely to hit network glitches; if a dependency ceases to exist, we have a copy; developers don't need to worry most of the time as keeping the repo pulled from the origin maintains all the dependencies - it's up to anyone _modifying_ dependencies to take extra steps) and not many downsides, apart from slower initial clone speed.

**Comment by spikymonkey** [comment]
I hit this today. Right now we're in the worst of possible worlds - `vendor` is missing some dependencies, _and_ `govendor sync` is unable to fetch them because SHAs in `vendor.json` don't line up with reality. The plugin only builds in CI because we `go get` it, which is bad because it'll pull in arbitrary versions of the dependencies. Needs fixing.

**Comment by glyn** [comment]
I suggest deleting the bad SHAs from `vendor.json` and then adding in the latest versions of the missing dependencies. If the tests pass, it should be fine.

**Comment by spikymonkey** [comment]
Yep that was my thought too :)
