### ISSUE TITLE
Improve encrypt value error response

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-cli-plugin#86]
We no longer support old versions of SCS and therefore the following error message no longer applies:

```
$ cf csev cs-test mykey
FAILED
Error obtaining config server URL: The /cli/instance endpoint could not be found.
This could be because the Spring Cloud Services broker version is too old.
Please ensure SCS is at least version 1.3.3.
```

We should probably change this error message to `Config Server instance [name] does not have an encrypt key defined.`.

**Comment by spikymonkey** [comment]
Hi @csterwa, how did you produce this error? Were you testing against a version < 1.3.3?

This message shouldn't happen if run against SCS 2 or 3. It's specific to the `/cli/instance` endpoint which should exist in both of those versions, so it's correct to say 'version is too old' if that's not found.

If no encrypt key is set, then `/cli/instance` should exist on the broker but `/encrypt` should not exist on the config server. We try to detect that case and report `Encryption failed or is not supported by this config server` if it happens.

**Comment by csterwa** [comment]
I ran the CLI against a 3.0 instance is all. I'll see if my plugin is not up to date.

**Comment by spikymonkey** [comment]
Ah okay thanks, in that case I would expect you to have got the `Encryption failed or is not supported by this config server` message, so this sounds like a problem. I'll try this out too

**Comment by spikymonkey** [comment]
This is what I got with the latest CLI plugin.

`mycs-2-no-encryption` is SCS 2 config server with no encryption key
`mycs-2` is SCS 2 config server with an encryption key
`mycs-3` is SCS 3 config server

```
±  |gareth/Improve_encrypt_value_error_response-86 ✓| → cf s
Getting services in org gareth / space dev as admin...

name                   service                       plan       bound apps   last operation     broker
mycbd-2                p-circuit-breaker-dashboard   standard                create succeeded   p-spring-cloud-services
mycs-2                 p-config-server               standard                update succeeded   p-spring-cloud-services
mycs-2-no-encryption   p-config-server               standard                create succeeded   p-spring-cloud-services
mycs-3                 p.config-server               standard                create succeeded   scs-service-broker
mysr-2                 p-service-registry            standard                create succeeded   p-spring-cloud-services

  MacBook-Pro-4 in ~/workspace/spring-cloud-services-cli-plugin
±  |gareth/Improve_encrypt_value_error_response-86 ✓| → cf csev mycs-2-no-encryption foo
FAILED
Encryption failed or is not supported by this config server: {"timestamp":"2019-05-03T14:04:40.665+0000","status":404,"error":"Not Found","message":"No message available","path":"/encrypt"}

  MacBook-Pro-4 in ~/workspace/spring-cloud-services-cli-plugin
±  |gareth/Improve_encrypt_value_error_response-86 ✓| → cf csev mycs-2 foo
7847cacfc358192909b686bd0b5457834d7842b17120aa4aa28e62827533dd24

  MacBook-Pro-4 in ~/workspace/spring-cloud-services-cli-plugin
±  |gareth/Improve_encrypt_value_error_response-86 ✓| → cf csev mycs-3 foo
FAILED
Encryption failed or is not supported by this config server
```
