### ISSUE TITLE
Add command for Config Server property refresh

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-cli-plugin#88]
In SCS 3.0.0, the `/actuator/refresh` endpoint is secured and enables manual refresh of property backends for the Config Server instance. A new command to refresh the properties would improve the experience for a Developer.

GIVEN valid PCF credentials with sufficient permissions, SpaceDeveloper or Admin in space with Config Server instance
AND a Config Server instance named `myconfig` with Git repositories configured
AND a change is made to a properties file in one of the configured Git repositories for `myconfig`
WHEN `cf config-server-refresh myconfig` is executed
OR `cf csr myconfig` is executed (shorthand)
THEN the property change should be provided by `myconfig`

**Comment by habuma** [comment]
While the desire to refresh config server properties via a CLI command makes sense, this story was written in the context of #772, which expected it possible to POST to the config server's /actuator/refresh endpoint. Per the comments left in that issue, that is not possible...at least not at this time. In short, the config server's /actuator/refresh endpoint does nothing and you must cf update-service to refresh the properties served by config server.

Should this story remain open? If so, then a separate story should be written such that the config server's /actuator/refresh endpoint (or some similar endpoint) actually does something. Even then, it's not the config server that needs refreshing, but the mirror service. So to implement this story, as well as the new story I'm suggesting, mirror service would need to provide a means of refreshing its mirror via an endpoint or some other means other than cf update-service on the config-server.

**Comment by csterwa** [comment]
I do think this is important for a patch release in the future. Just as in the other associated story, I think we should implement the API that we need in order to support this as you pointed out.

**Comment by alek-sys** [comment]
@csterwa I've used `config-server-refresh` and `csr` vs `scs-config-server-refresh` and `scs-scr` to be consistent with encrypt command which is `config-server-encrypt`. Do you want to have this `scs` prefix? Happy to change it for both commands.

**Comment by csterwa** [comment]
I'd like to be consistent with scs- prefix

**Comment by csterwa** [comment]
@alek-sys I've updated the Gherkin to use `config-server-refresh` and short-hand of `csr` for the commands.

**Comment by csterwa** [comment]
```
$ cf csr application-config-sample
Successfully refreshed mirrors
```
