### ISSUE TITLE
Support for adding secrets to credhub in spring cloud config server 3.x

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/spring-cloud-services-cli-plugin#92]
Is there plans to support adding secrets to credhub with this cf cli plugin: https://docs.pivotal.io/spring-cloud-services/3-0/common/config-server/managing-secrets-with-credhub.html#adding-a-secret

**Comment by csterwa** [comment]
@xyloman yes, our intention is to add commands for this. We will prioritize this into our backlog for Spring Cloud Services. We don't have an ETA on its release yet. We'll attach PRs to this issue so you will be notified.

**Comment by csterwa** [comment]
Acceptance test definition for the new commands:

GIVEN an existing `p.config-server` instance named `myconfig`
WHEN `cf config-server-add-credhub-secret myconfig myprop mysecret` is executed
THEN `myconfig` should have `myprop` available with value `mysecret` from CredHub

GIVEN an existing `p.config-server` instance named `myconfig`
WHEN `cf config-server-remove-credhub-secret myconfig myprop` is executed
THEN `myconfig` should no longer have `myprop` available in CredHub

GIVEN an existing `p.config-server` instance named `myconfig` DOES NOT exist
WHEN `cf config-server-add-credhub-secret myconfig myprop mysecret` is executed
THEN the command should fail with response "Service instance myconfig does not exist"

GIVEN an existing SCS 2.x `p-config-server` instance named `oldconfig`
WHEN `cf config-server-add-credhub-secret oldconfig myprop mysecret` is executed
THEN the command should fail with response "Service instance oldconfig does not support this command"
